config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: 'Restaurant was successfully  created.'
    else
      render :new
    end
  end

  def show
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">BestMissCocktail</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="tn btn-ghost my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

app/views/cocktails/new.html.erb
<%= render 'navbar', cocktail: @cocktail %>

<div class="container">
  <h1>New cocktails</h1>

<div class="formulaire">
<div class="col-6 offset-3">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Ajouter', class: "btn btn-ghost" %>
  <% end %>
</div>
</div>
<%= link_to 'Back', cocktails_path, class: "btn btn-ghost" %>
</div>

app/views/cocktails/show.html.erb
<%= render 'navbar', cocktail: @cocktail %>

<div class="container">
<h1>Comment préparer un <%= @cocktail.name %> ?</h1>

<div class="card-cocktail">
  <div class="cocktail-img">
    <% if @cocktail.photo.attached? %>
        <%= cl_image_tag @cocktail.photo.key, height: 300, width: 300, crop: :fill %>
    <% end %>
  </div>

  <div class="cocktail-recipe">
    <h3><%= @cocktail.name %></h3>
    <br>
    <p>Recipe</p>
    <hr>
    <ol>
    <% @cocktail.doses.each do |dose| %>
      <li><%= dose.description %> de <%= dose.ingredient.name %>
      <%= link_to '🗑', dose_path(dose), method: :delete, data: { confirm: 'Are you sure ? '} %>
      </li>
    <% end %>
    </ol>
    <%= link_to 'Add a dose',  new_cocktail_dose_path(@cocktail), class: "btn btn-ghost" %>
  </div>
</div>

<%= link_to 'Back', cocktails_path, class: "btn btn-ghost" %>
</div>

app/views/doses/new.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">BestMissCocktail</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="tn btn-ghost my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

<div class="container">
<h1>Add a new dose to <%= @cocktail.name %></h1>

<div class="formulaire">
<div class="col-6 offset-3">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>

    <%= f.submit 'Add', class: "btn btn-ghost" %>
  <% end %>
  <br>
</div>
</div>
  <%= link_to 'Back', cocktails_path, class: "btn btn-ghost" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BestMissCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
      <%= yield %>
  </body>
</html>